- cluster.go
- driver.go
- integration_test.go
Also re-enable handling of large queries split into multiple responses, since it
was not the issue.
> Update the registry index after catching up with logs with Barrier()

- driver.go
- internal/bindings/conn.go
- internal/client/client.go
Make it possible to configure the default context timeout for client requests. See https://github.com/lxc/lxd/issues/5234.
> Add support for configuring the default context timeout

- internal/bindings/server.go
This is useful when running multiple servers in the same process, e.g. unit
tests.
> Support disabling SQLITE_CONFIG_SINGLETHREAD

- driver/driver.go
- internal/bindings/errors.go
Makes it easier to check if a transaction should be retried, see https://github.com/canonical/dqlite/issues/164.
> Expose err busy

- internal/protocol/message.go
A fix for my previous feature enhancement (discovered thanks to sqlalchemy's thrashings...)
The non-destructive reads were not resetting when encountering an EOF, so this resets accordingly under that condition.
> fix corner case of scanning for column types and encountering EOF

- .dir-locals.el
- driver/driver.go
- driver/driver_test.go
- driver/integration_test.go
- internal/protocol/message.go
This fixes a corner case where If a client requests the column types and it is already at the last row, it will return the cached values from the previous read.
This assumes that the column types *cannot* change from row to row.
> cache column types to allow reporting on same at end of rows

- cmd/dqlite-demo/cluster.go
I noticed it was possible to `add` nodes to a cluster that doesn't use localhost / the standard ports, but the `cluster` command didn't allow this. 
Seemed quite straightforward to add this via the `--cluster` parameter which `add` uses.
> Add --cluster parameter to cluster command

- client/client_test.go
- cmd/dqlite-demo/cluster.go
- driver/driver.go
- driver/integration_test.go
After fixing my other open PR I encountered erratic test results on my local instance, and there was a TODO on making timing configurable so I've added that functionality.
A couple of pauses were inserted in the tests because the given timeouts were not quite enough. Local testing now appears to pass consistently.
> Add driver connection options

- driver/integration_test.go
- internal/protocol/connector.go
Add integration tests for errors happening when binding query parameters, and improve connection logging.
> Bind error integration tests

- client/client.go
- client/leader.go
- driver/driver.go
- driver/integration_test.go
- internal/protocol/config.go
- internal/protocol/connector.go
- internal/protocol/connector_test.go
- internal/protocol/protocol.go
This branch moves closer to remove hard-coded timeouts in the code base and have them instead controlled by the user with ```context.Context``` objects.
A few APIs have been deprecated to signal that users writing new code should favor context-aware APIs instead.
> Cleanup timeout logic

- client/client_test.go
- driver/driver.go
- internal/protocol/connector.go
- internal/protocol/message.go
- internal/protocol/message_export_test.go
- internal/protocol/message_internal_test.go
- internal/protocol/protocol.go
- internal/protocol/protocol_test.go
- internal/protocol/request.go
- internal/protocol/schema.sh
The previous implementation was using 2 buffers for sending and receiving messages: a one-off allocated buffer of fixed size reused across messages (to avoid re-allocation) and a dynamically sized one allocated for sending or receiving specific messages exceeding the size of the one-off buffer.
That was an optimization that probably didn't buy much performance, and apparently was the source of some bugs surfaced in k8s.
This branch moves to a single buffer, which is grown as needed and not re-allocated. This should maintain the performance benefits of the previous approach (however small, this would need to be measured), but simplifies the underlying logic making it more robust. The only downside is that this buffer is never shrunk once grown, if that becomes a problem in practice we can …
> Use a single buffer for sending and receiving messages

- driver/driver.go
It turns out that this is a bit too verbose.
> Downgrade log level of lost leadership from Warn to Debug

- .travis.yml
- driver/driver.go
- driver/integration_test.go
The values of some constants had to be bumped since they were conflicting with
upstream.
> Update some error constants to match SQLite 3.32.1+replication4

- .gitignore
- .travis.yml
- app/app.go
- app/app_test.go
- app/files.go
- cmd/dqlite-demo/dqlite-demo.go
- test/dqlite-demo.sh
When a non-bootstrap node first starts it will try to join the cluster asynchronously, so it can retry in case of failures and it won't block the `app.New()` call.
An integration test has been added as well to validate that the demo program behaves as advertised in `README.md`.
> Make initial cluster joining asynchronous

- app/app.go
- app/app_test.go
- app/options.go
- cmd/dqlite-demo/dqlite-demo.go
- test/dqlite-demo.sh
This is an initial stab at including in the `app` framework the same goodness we have in LXD and microk8s. Joining nodes will be assigned the `Voter` role only once the cluster reaches 3 nodes. More refinements will follow, as well as handling of edge cases.
> Don't join as Voter if there are less than 3 nodes

- app/app.go
- app/example_test.go
- app/options.go
- cmd/dqlite/dqlite.go
- internal/shell/options.go
- internal/shell/shell.go
- node.go
This PR also adds a few other improvements:
- initial support for json output in dqlite shell
- avoid requiring the `WithAddress()` option for restarts
- new .remove command in `dqlite` CLI
- support specifying a store file for the `dqlite` CLI instead of a manual list of nodes
> Add ReconfigureMembership() to force a new raft configuration

- .dir-locals.el
- .travis.yml
- app/app.go
- app/app_test.go
- app/options.go
- app/roles.go
- client/client.go
- client/client_test.go
- internal/bindings/server.go
- internal/protocol/constants.go
- internal/protocol/request.go
- internal/protocol/response.go
- internal/protocol/schema.go
- node.go
- test/roles.sh
Honor user-defined failure domains and weights when picking role handover targets upon node shutdown and replacement targets upon node crash. For now roles of online healthy nodes won't be changed.
> Honor failure domains and weights

- README.md
Noticed the link was broken since fd3d40d8acf0501a4d0c9bc4a304ab706aae0b98 just offering a quick fix.
> update link to demo

- app/app.go
- app/app_test.go
This handles the case of a two-node cluster with one voter and one spare, and
the voter being shutdown gracefully.
> app: Don't attempt to transfer leadership before promoting the other node

- go.mod
- go.sum
Somewhat counterintuitively the latest version of go-sqlite3 is v1.14.5
as opposed to v2.0.3. Apparently updating to v2 was a mistake, as noted
in https://github.com/mattn/go-sqlite3/blob/master/README.md#go-sqlite3.
Trying to use the latest versions of go-dqlite and go-sqlite3 in a
project resulted in a kind of go.mod edit war. This therefore updates
the go-sqlite3 dependency to the latest version.
> Update go-sqlite3 package to v1.14.5

- app/proxy.go
In all other paths we simply call remote.Close and local.Close but in
this specific part we call CloseRead():
- I would just like to know why we use CloseRead() and not Close()
- The proxy() function is called from
```go
func (a *App) proxy() {
wg := sync.WaitGroup{}
ctx, cancel := context.WithCancel(context.Background())
for {
client, err := a.listener.Accept()
if err != nil {
cancel()
wg.Wait()
close(a.proxyCh)
return
}
address := client.RemoteAddr()
a.debug("new connection from %s", address)
server, err := net.Dial("unix", a.nodeBindAddress)
if err != nil {
a.error("dial local node: %v", err)
client.Close()
continue
}
wg.Add(1)
go func() {
defer wg.Done()
if err := proxy(ctx, client, server, a.tls.Listen); err != nil {
a.error("proxy: %v", err)
}
}()
}
}
```
and it seems to me that by …
> proxy: close remote

- app/app.go
- app/proxy.go
- app/proxy_darwin.go
- app/proxy_linux.go
Found a couple of ways to make the logic cross-platform in golang, so seems the patch is actually ready to be a part of the master branch.
Overall the change allows to build demo & deps (with patches to the latest releases) on MacOS and connect to the other nodes (Lin/Mac) using TLS.
To make the TLS work properly on Mac - it uses the regular socket file (abstract one are supported on Linux only) and it's created in the CWD of the process. I think it's the best way to implement, since we can't use `/tmp` or `/var/run` on Windows later.
* MacOS -> MacOS - works well
* Linux -> MacOS - works well
* MacOS -> Linux - joined and looks like the demo is working well
The other patches in series:
* canonical/dqlite#285
* https://github.com/canonical/dqlite/pull/288
* …
> Build on MacOS with TLS support

- .github/workflows/build-and-test.yml
- README.md
- app/app.go
- app/app_test.go
- app/options.go
- internal/bindings/build.go
- internal/bindings/server.go
- node.go
This PR uses the new dqlite API `dqlite_node_set_snapshot_params` available from dqlite `1.8.0`.
I want to update the SONAME of dqlite from `libdqlite.so.0` to `libdqlite.so.1` so that go-dqlite binaries built against a version of dqlite that contain this API fail when ran against an older version of the dqlite library. The problem is, I already released a version of libdqlite with SONAME `libdqlite.so.0` that contains the `dqlite_node_set_snapshot_params` functionality.
I'm not entirely sure if I should:
a) make a new dqlite release `1.9.0` and update the SONAME ? <-- This probably seems most reasonable
b) just update the SONAME on master and not make a release ?
c) ... ?
> app: node: Add raft snapshot parameter options

- app/app.go
- app/files.go
- client/store.go
- go.mod
There are some mentions of corrupted / empty `cluster.yaml` files. This PR should help prevent these cases.
- Atomically replace files when writing by using the [renameio](https://github.com/google/renameio) package.
- Protect against empty server list (if an empty list is ever even possible).
Fixes https://github.com/canonical/go-dqlite/issues/145
> More robust filewriting

- go.sum
- internal/protocol/connector.go
Quick win to check voters first when contacting servers to find a leader.
> connect: sort servers by Role

- internal/shell/shell.go
Looks like the converting the row to a string takes a large amount of time, these changes amount to approx. a 4x speed increase when performing `select * from kine LIMIT 10000;` on a large kine database. Expect the speedup to be similar for other use cases.
> shell: Speedup row printing

- driver/driver.go
Overlap with SQLITE_BUSY_RECOVERY and SQLITE_BUSY_SNAPSHOT errors that
can occur in WAL-enabled sqlite databases.
> driver: Add additional busy err codes.

- .github/workflows/packages.yml
Ubuntu 18.04 ships with Go 1.10 which is too old for dqlite.
> github: Disable packages on bionic

- app/app.go
- app/app_test.go
- go.mod
- go.sum
- internal/protocol/message_internal_test.go
- Fix test checking alignment of slice instead of the data contained in the slice.
- Parallelize `makeRolesChanges`. This function probes all nodes for connectivity, performing the probe sequentially could take a while in some cases.
- Increase timeout on the RolesAdjustment tests. The changes in timing might look a bit extreme, but in real-life the `RoleAdjustmentFrequency` is set to 30 seconds, which is still a lot less frequent than in the tests.
Lowering the `RoleAdjustmentFrequency` lowers the load on the testmachines (especially an underpowered armhf machine), they have to setup a lot less TLS connections. I blame TLS for the flakyness of the tests on the armhf machine because when it is turned off, the tests run a lot faster, don't max out the CPU and are not flaky anymore.
An …
> Armhf test fixes

- app/tls.go
As we are performing a lot of TLS handshakes with the same set of nodes over and over, a client session cache should speed up the handshake process.
> tls: Add ClientSessionCache

- internal/protocol/message.go
This aligns to the default behaviour of go-sqlite3 (without the `_loc` DSN argument) that does not convert by default.
Otherwise this causes some undesirable behaviour when writing back a time.Time value retrieved from the database, as it will cause the value in the database to be mutated incorrectly to the local time, unless it is manually converted back to UTC.
Fixes https://github.com/lxc/lxd/issues/9747
Signed-off-by: Thomas Parrott <tomp@tomp.uk>
> internal/protocol/message: Don't convert retrieved datetimes to local timezone

- app/app.go
- app/app_test.go
- app/dial.go
- app/options.go
- app/proxy.go
This takes a bunch of the logic from the dqlite proxies in lxd's `Gateway` and applies them to `app.App` via a `WithExternalConn` option.
`WithExternalConn` takes a `client.DialFunc` and an `acceptCh` which will be used for back and forth handling of the external connection. 
I modified the TLS keep alive options a little to look more like how we handle them in LXD [here.](https://github.com/lxc/lxd/blob/ddc19d45afd6344fa21d2db0a6e0fbf31c50a36c/lxd/util/net.go#L333-L376)
> Add WithExternalConn to app.App

- app/app.go
- app/dial.go
- internal/bindings/server.go
- internal/bindings/server_test.go
- internal/protocol/connector_test.go
- node.go
Adds a context to the dqlite server `Node` struct which starts on creation and is cancelled on close. This context is passed to the C bindings and stored in a `contextRegistry`, from which the `dialCtx` is derived.
As well, The `App` context is passed to the proxied dial functions for external connections and TLS.
> Don't use background context for c bindings.

- go.mod
- go.sum
- internal/protocol/connector.go
- internal/protocol/connector_test.go
Fix tests as result of API breakage of updated package.
fixes https://github.com/canonical/go-dqlite/issues/190
> go.mod: Update Rican7/retry to v0.3.0

- internal/bindings/server.go
If dqlite_node_create fails, the `struct dqlite_node *` argument is set to NULL, so we shouldn't try to dereference it.
Discovered while investigating https://github.com/canonical/raft/issues/228.
> internal/bindings/server: don't use bad dqlite_node

- app/app.go
- app/options.go
- app/proxy.go
- benchmark/benchmark.go
- driver/driver.go
- internal/shell/shell.go
We use the conventional Go style: no initial capitalization, no final
punctuation. See
https://github.com/golang/go/wiki/CodeReviewComments#error-strings.
As discussed in #196.
> style: Normalize error strings

- app/app.go
In the `Handover` method of `App`, after successfully transferring leadership to another node, we shouldn't continue looping over other servers and trying to transfer to them. Spotted by @MathieuBordere.
> app: Don't transfer leadership more than once

- .github/workflows/build-and-test.yml
We already run `go test` on Launchpad, but not for pull requests. Not sure whether there's a reason for that, so I'm opening this PR to facilitate discussion.
> github: Run go test in CI

- .github/workflows/build-and-test.yml
Reverts #201. @MathieuBordere pointed out that overalls already runs all tests in the project, including printing a report for test failures. So we don't need to run `go test ./...` separately after all.
https://github.com/canonical/go-dqlite/blob/bca58cd1b7af8555ce118b45f34e95330f397307/.github/workflows/build-and-test.yml#L46
> Revert "github: Run go test in CI"

- README.md
- cmd/dqlite-demo/dqlite-demo.go
Fixes some behaviour observed in: https://github.com/canonical/go-dqlite/issues/203
I was freaking out somewhat about the shell showing byte arrays instead of strings, I thought we had a bug somewhere in the encoding / decoding of types, took me a bit to investigate.
> Dqlite demo fixes

- cmd/dqlite/dqlite.go
- internal/shell/shell.go
- Fix a bug where a user could lock a running database by issuing a failing transaction that was never rolled back. Some projects use the shell so could happen in non-toy examples. I ran into it when trying to insert a row that violates a UNIQUE key constraint, locking my DB for further inserts.
- Add successful commands to the shell history (by default limited to 1000 entries). Up & Down arrow keys will behave as expected in the `dqlite` shell.
> Shell fixes

- app/app.go
- app/options.go
It makes sense to require that the configured number of voters be odd, because that avoids ties in raft elections. But I don't see any reason to require that the number of standby nodes be odd. Please correct me if there's something I'm missing!
> Don't require number of standbys to be odd

- cmd/dqlite-benchmark/dqlite-benchmark.go
> dqlite-benchmark: Backticks messed up help text

- .github/workflows/build-and-test.yml
- app/example_test.go
- app/tls.go
- cmd/dqlite-benchmark/dqlite-benchmark.go
- cmd/dqlite-demo/dqlite-demo.go
- driver/integration_test.go
- internal/protocol/dial.go
This PR introduces:
- Update SimpleTLSConfig: The current config doesn't seem to be compatible with `go 1.19.6` making connections fail with `write handshake: local error: tls: bad record MAC` see e.g. [here](https://github.com/canonical/go-dqlite/actions/runs/4342334566/jobs/7583025948), don't know root cause yet and it's probably not a good idea to wait for a new go release if it would indeed be a bug in go (which it is probably not). 
The config in this PR fixes the issue. Anyone has an opinion on the proposed config in this PR?
- Run CI on Ubuntu 22.04.
- Disable running CI on Ubuntu 18.04
- Add go versions until 1.19 to CI.
- Fix some issues when upgrading to `go 1.19.x` 
- removing `deadcode`, `overalls`
- used buffered channel for os.Signal
- make sure there's only 1 Output comment …
> Add go 1.19

- app/app.go
- app/app_test.go
- app/options.go
The following provides the tracing options at the app level, so we can then pass them directly to the driver. This will allow monitoring of the traces provided by the driver.
This approach will suffice for now, but might be better to rethink how we expose driver capabilities in the future.
Fixes: #242
> Provide tracing options at the app level

- internal/shell/shell.go
Use .help to explain to a shell user what options are available. This help prompt will provide a good starting point users are faced with the shell repl.
Fixes: #240
> Shell .help built-in command

- driver/driver.go
Fixes https://github.com/canonical/go-dqlite/issues/182
> driver: Detect EOF in driverError

- test/dqlite-demo-util.sh
- test/recover.sh
- test/roles.sh
For the general "downstream testing" push, I would like to be able to run all the go-dqlite tests against a libdqlite.so that was built with ASan. For shell script tests that call `go build` explicitly, we need to allow adding `-asan` to the invocation, and that's what this PR implements.
> test: Allow building test binaries with -asan

- driver/driver.go
- tracing/tracing.go
To aid with debugging and development, the following implements the ability to trace requests to the driver. This includes adding the current SQL from conn methods ExecContext or QueryContext, and also adding the stmt ExecContext and QueryContext. Unfortunately, we can't trace every method as the go driver library doesn't allow passing a context to Commit or Rollback.
This is the lightest touch with adding tracing. The tracing code does not require any external dependencies, as this retrieves a Tracer from the passed-in context. As long as the Tracer conforms to the tracing.Tracer interface then a trace can be performed.
There will always be a Tracer if one isn't located on the context.
Potentially, this could supersede the current tracing implementation and remove the need to have a …
> OpenTelemetry Driver Tracing

- .github/workflows/build-and-test.yml
Raft is a dependency of the libdqlite-dev package, and mentioning it by name here causes problems since we started using the name `raft-canonical` (etc.) in the PPA.
> github: Don't install libraft-dev package

- internal/protocol/connector.go
I am working on https://github.com/canonical/go-dqlite/issues/134
The PR I have to resolve that issue is cleaner if I first push setting of the protocol version down into `connectAttemptOne` from `connectAttemptAll`.
Consider merging this before I rebase and submit a PR for #134
> Set protocol version inside connectAttemptOne

- internal/protocol/connector.go
This PR implements the solution discussed in my [first PR](https://github.com/canonical/go-dqlite/pull/290)
1. Spawn connection attempts in goroutines
2. Goroutines
a. Grab semaphore, defer release
b. Check if a connection has been found, exit
c. Execute original logic, write protocol output to channel
Resolves #134
> Attempt to connect to leader via 10 servers simultaneously

- cmd/dqlite/dqlite.go
Change the policy from retrying indefinitely to having a timeout to improve user experience. The timeout is configurable via a CLI flag (`--timeout`) and defaults to 2s.
> set client timeout in dqlite demo

- internal/protocol/message.go
- internal/protocol/message_internal_test.go
While gathering the first profiles for Kine, I noticed a big performance footprint in `Message.getBlob`. The fix is trivial and I added a benchmark to make sure it actually is useful.
I'm attaching the [before](https://github.com/user-attachments/files/15514156/before.txt) and [after](https://github.com/user-attachments/files/15514157/after.txt) output for `go test -benchmem -run=^$ -bench BenchmarkMessage_getBlob -count 10` run on my machine.
The `benchstat` output shows promising results (and the function disappears from my flamegraph):
```
goos: linux
goarch: amd64
pkg: github.com/canonical/go-dqlite/internal/protocol
cpu: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
│  before.txt   │              after.txt               │
│    sec/op     │    sec/op     vs base                │ …
```
> Improve Message.getBlob performance

- app/app.go
- app/options.go
After starting the `go-dqlite` `App`, it continually checks for role adjustments and updates the local store of nodes. The frequency of this check can be managed by `WithRolesAdjustmentFrequency`. 
From the perspective of a project using `go-dqlite` it would be very useful to hook into this continual check to piggy-back heartbeats off of, or generally keep an up-to-date record of what dqlite sees.
To that end, this PR introduces the `WithRolesAdjustmentHook` option to `app.App` which is run after attempting a role adjustment. It will provide a client to the current dqlite leader, as well as a list of the most recently updated dqlite nodes so that the project using `go-dqlite` can update its own state without having to send further requests over the network to determine this information.
> Hook into continual dqlite role probes

- app/app.go
This PR uses range loop instead of infinite loop + recv from channel as it is difficult during application tear-down to synchronize between application shutdown and listener closing. If for some reason the `acceptChan` is closed while the goroutine is still waiting, the received connection is `nil` and makes the code panic.
Using range loop over the channel solves the problem, makes the code more robust and (arguably) more idiomatic.
> Use range loop instead of endless loop

- app/app.go
- app/options.go
- client/client.go
- client/leader.go
- driver/driver.go
- internal/protocol/config.go
- internal/protocol/connector.go
Recently, `go-dqlite` was updated in #292 to concurrently open up to 10 requests to other cluster members when probing for leadership. The goal of this was to prevent go-dqlite from getting hung up on some unresponsive nodes. 
One issue with this is that it is a bit too aggressive, each attempt to fetch the leader will execute effectively `2n - 1` network requests where `n` is the number of cluster members. #302 will make this return early if the leader is found, but it would also be great if a project could configure this value to grow and shrink based on the current health of the cluster. 
Effectively, if the cluster is healthy, the `2n -1` requests are redundant because we generally only need a maximum of 2. (One to some node and another to who that node reports is the leader). 
So …
> Configure maximum concurrent leader probes

- driver/driver.go
These are stable and potentially useful for clients.
> driver: Expose leadership-related error codes

- node.go
> node: Document usage of ReconfigureMembership and ReconfigureMembershipExt

- driver/driver_test.go
- internal/bindings/server.go
- node.go
- node_test.go
Closes #299. CI will fail until the dqlite PR merges, and we'll need to either bump the minimum supported libdqlite version or add a shim to support older dqlite versions that lack this function.
> Add a wrapper for dqlite_node_describe_last_entry

- .github/workflows/build-and-test.yml
- .github/workflows/daily-benchmark.yml
- .github/workflows/static.yml
- app/app.go
- app/app_test.go
- app/options.go
- app/proxy.go
- benchmark/benchmark.go
- client/store_test.go
- cmd/dqlite-benchmark/dqlite-benchmark.go
- driver/driver_test.go
- driver/integration_test.go
- internal/bindings/server.go
- internal/bindings/server_test.go
- internal/protocol/errors.go
- internal/protocol/message.go
- internal/shell/shell.go
- node.go
Clean up our CI jobs in various ways:
- Only test on the minimum supported Go version (1.13) and the latest version, instead of every version in between.
- Drop golint (deprecated, not in Noble)
- Remove unused `overalls` install
- Remove references to disk mode
- Split out static analysis into its own job that runs with only one Go version, and add staticcheck
- Fix reports from staticcheck
> CI cleanups

- app/tls.go
According to the [Go docs](https://pkg.go.dev/crypto/tls#Config) for `tls.Config` (comment on the SessionTicketsDisabled field):
> Note that on clients, session ticket support is also disabled if ClientSessionCache is nil.
Before this change, SimpleDialTLSConfig implicitly set that field to nil, so it wasn't taking advantage of session resumption.
Note that this doesn't immediately impact any downstreams unless they are using our SimpleTLSConfig. However, it seems worth doing regardless, since the comments in tls.go suggest that SimpleTLSConfig is intended to take advantage of session resumption. At any rate, the app test suite should be more efficient now.
Thanks @marco6 for suggesting to look into this.
> Enable client session cache for App TLS
