canonical/go-dqlite

internal/bindings/server.go, internal/bindings/server_test.go
This avoids Go's garbage collector closing the original fd (since the stdlib
uses SetFinalizer).
=> Get a new fd with dup() before passing it to C

internal/bindings/server.go
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
=> bindings: Mark all fds as CLOEXEC

config.go, driver/driver.go, driver/integration_test.go, internal/bindings/server.go, internal/protocol/connector_test.go
=> Add ConfigMultiThread

driver/driver.go, driver/integration_test.go, internal/protocol/message.go
Having column type support is a handy thing for ORMs.
=> add support for database column types

driver/driver.go
Workaround for https://github.com/canonical/dqlite/issues/210
=> Execute a no-op exec command to force the raft log to be replayed

.gitignore, README.md, app/app.go, cmd/dqlite/dqlite.go, internal/shell/options.go, internal/shell/shell.go
Initial implementation of a SQLite-like shell with basic features.
=> Command line shell

app/app.go
Within snaps the name of the choosen Unix domain socket has to be
special crafted. See https://github.com/snapcore/snapd/blob/master/interfaces/apparmor/template.go#L357
for more details
=> app: choose snap suitable socket name to satisfy AppArmor confinement

app/app.go, client/store.go, driver/driver.go, driver/driver_test.go
Teach `DefaultNodeStore` to guess the type of the file by conventionally looking at its extension.
=> Smarter DefaultNodeStore() and other misc improvements

client/dial.go, client/leader.go, driver/driver.go, internal/protocol/connector.go, internal/protocol/connector_test.go, internal/protocol/constants.go, internal/protocol/dial.go, internal/protocol/protocol.go, internal/protocol/protocol_test.go, internal/protocol/response.go, internal/protocol/schema.sh
A number of improvements around the `protocol.Connector` struct.
=> Connector clean up

.travis.yml, app/app.go, app/app_test.go, app/options.go, cmd/dqlite-demo/dqlite-demo.go, cmd/dqlite/dqlite.go, test/dqlite-demo.sh, test/roles.sh
This branch adds to the `app` package the same roles management goodness that LXD and microk8s currently enjoy.
=> Dynamic roles management

app/app.go, test/roles.sh
Several assorted fixes around the newly introduced roles management logic.
=> Clean up rough edges in roles management

app/app.go, app/roles.go
There are no logic changes, it's just an API cleanup in order to have something
nicer for external users to consume.
=> app: Expose roles changes algorithm via the RolesChanges struct

internal/bindings/server.go
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
=> internal/bindings/server: don't leak file descriptor

app/app_test.go, driver/integration_test.go, test/dqlite-demo.sh, test/roles.sh
Fixes a couple of "infinite" hangs and flaky unit tests.
=> CI test fixes

README.md
While the examples work, this I think is better documentation.
=> Swap my-key and my-value

cmd/dqlite/dqlite.go
Fixes https://github.com/canonical/go-dqlite/issues/154
=> dqlite: Check if servers file exists in cli

app/app.go, app/app_test.go
Signed-off-by: Max Asnaashari <max.asnaashari@canonical.com>
=> External Connection: Write hijacked response header

app/app.go, app/options.go
Signed-off-by: Stéphane Graber <stephane.graber@canonical.com>
=> app: Add WithUnixSocket

driver/driver.go, driver/driver_test.go, internal/protocol/message.go
Don't silently overflow number of parameters in tuple.
=> driver: Prevent overflowing the amount of parameters

.github/workflows/packages.yml
=> packages: remove impish; add kinetic

app/app.go
Fixes https://github.com/canonical/go-dqlite/issues/228 .
In the issue above the demotion of the old leader fails because the new transferred to leader is still applying it's no-op barrier entry at the start of its term, resulting in an uncommitted configuration change while that barrier has not been committed. The retry logic works around this, because the barrier will eventually commit and the demotion can continue.
This reminds us of the issue that @cole-miller brought up a while ago, that when trying to update the raft configuration we would also need a barrier.
I'm okay with the semantics that a config change can fail because another one is ongoing and that a client should just retry it.
=> app: Retry Handover until ctx times out.

cmd/dqlite-demo/dqlite-demo.go
Adds TLS support to `dqlite-demo`.
=> dqlite-demo: Add TLS options

driver/driver.go, internal/protocol/message.go
=> Fix int overflow on 32-bit archs

.github/workflows/packages.yml
=> Only publish to PPA from master

driver/driver_test.go
Actually test sending an interrupt.
=> driver_test: test interrupting query yielding rows.

internal/protocol/connector.go
=> Avoid context cancellation during net.Dial call in connector

cmd/dqlite-demo/dqlite-demo.go
Have dqlite-demo return an HTTP error response to requests that don't succeed, instead of always returning 200.
=> dqlite-demo: Reflect operation status in HTTP code

internal/shell/shell.go
Without column headers, it's non-obvious what each column value is without referring to the original schema. To remove the ambiguity and make it easier to read the output this adds a tabwriter from the standard library.
The output is a lot cleaner IMO, but you do lose the separator lines. We could add it back using an external package, but I'm unsure it's worth it.
Fixes: #313
Example output becomes:
```
dqlite> SELECT * FROM charm_origin
charm_uuid                              source_id       id      revision        version
a22ff9d2-3da4-4653-8e00-ea85aa045546    1               <nil>   9               <nil>
03a7ab56-9522-4e46-8f5d-79af83fc762e    1               <nil>   10
```
=> feat: tab writer

.github/workflows/build-and-test.yml
=> github: Switch to official Coveralls action with parallel support

.github/workflows/packages.yml
=> PPA: remove mantic, add oracular
